name: 'Fetch PR Details Between Merges'
description:
  'Retrieve pull requests, their SHAs, and authors between two specified merge
  commits.'
inputs:
  github-token:
    description: 'GitHub token used for authentication with the GitHub API.'
    required: false
    default: ${{ github.token }}
  repo-owner:
    description: 'Owner of the repository (user or organization).'
    required: false
    default: ${{ github.repository_owner }}
  repo-name:
    description: 'Repository name where the action will run.'
    required: false
    default: ${{ github.event.repository.name }}
  from-sha:
    description: 'SHA of the first merge commit.'
    required: true
  to-sha:
    description: 'SHA of the second merge commit.'
    required: true
outputs:
  pr-details:
    description: >
      JSON formatted string containing details of all pull requests between the
      specified commits. The format of each pull request object is as follows: -
      "number": The pull request number. - "title": The title of the pull
      request. - "sha": The commit SHA of the pull request. - "author": The
      GitHub username of the author. - "mergedAt": The timestamp of when the
      pull request was merged.

      Example output: values: [
        {
          "number": 123,
          "title": "Fix login issue",
          "sha": "abcd1234efgh5678ijkl9101mnopqrstuvwx",
          "author": "johndoe",
          "pr_md_link":
      "<https://github.com/<organization>/<repository>/pull/123|Fix login
      issue>"
        },
        {
          "number": 124,
          "title": "Add new feature for handling API requests",
          "sha": "wxyz5678abcd9101efgh2345ijklmnopqrst",
          "author": "janedoe",
          "pr_md_link":
      "<https://github.com/<organization>/<repository>/pull/124|Add new feature
      for handling API requests>"
        }
      ]
runs:
  using: 'node20'
  main: 'dist/index.js'
