name: 'Fetch PR Details Between Merges'
description:
  'Retrieve pull requests, their SHAs, and authors between two specified merge
  commits.'
inputs:
  github-token:
    description: 'GitHub token used for authentication with the GitHub API.'
    required: true
  repo-owner:
    description: 'Owner of the repository (user or organization).'
    required: true
  repo-name:
    description: 'Repository name where the action will run.'
    required: true
  from-sha:
    description: 'SHA of the first merge commit.'
    required: true
  to-sha:
    description: 'SHA of the second merge commit.'
    required: true
outputs:
  pr-details:
    description:
      'JSON formatted string containing details of all pull requests between the
      specified commits.'
runs:
  using: 'node20'
  main: 'dist/index.js'
